Repository fi-ksi/web-frontend-angular, pull requests merged in 2022-10, with the labels that each got.

#65 Fix picture proportions
  src/app/components/root/page-welcome/page-welcome.component.scss
Labels: hacktoberfest-accepted

#66 fix(module): programming buttons underflow
  src/app/components/tasks/task-module/task-module-programming/task-module-programming.component.scss
Labels: hacktoberfest-accepted

#68 fix(page-results): sort scores by their value
  src/app/components/results/page-results/page-results.component.ts
Labels: bug, hacktoberfest-accepted

#70 Feat/discussion deletion
  src/app/components/shared/discussion-thread/discussion-thread-posts/discussion-thread-posts.component.html
  src/app/components/shared/discussion-thread/discussion-thread-posts/discussion-thread-posts.component.ts
  src/assets/i18n/cs.json
Labels: enhancement, hacktoberfest-accepted

#71 feat(footer): add external links and logos
  src/app/components/root/footer/footer.component.html
  src/app/components/root/footer/footer.component.scss
  src/assets/img/logos/brkos.svg
  src/assets/img/logos/email.svg
  src/assets/img/logos/facebook.svg
  src/assets/img/logos/fi.svg
  src/assets/img/logos/github.svg
  src/assets/img/logos/ibis.svg
  src/assets/img/logos/intersob.svg
  src/assets/img/logos/kscuk.svg
  src/assets/img/logos/ksp.svg
  src/assets/img/logos/los.svg
  src/assets/img/logos/mu.svg
  src/assets/img/logos/youtube.svg
  src/assets/img/logos/zverinec.svg
Labels: hacktoberfest-accepted

#72 feat(task): support both collapse formats
  src/app/components/tasks/task-body/task-body.component.ts
Labels: hacktoberfest-accepted

#73 fix: date timezone offset
  src/app/components/admin/page-admin-tasks/page-admin-tasks.component.html
  src/app/components/news/page-article/page-article.component.html
  src/app/components/shared/article-preview/article-preview.component.html
  src/app/components/shared/discussion-thread/discussion-thread-posts/discussion-thread-posts.component.html
  src/app/components/shared/shared.module.ts
  src/app/components/tasks/page-task/page-task.component.html
  src/app/components/tasks/task-icon/task-icon.component.html
  src/app/components/tasks/wave/wave-task-linear/wave-task-linear.component.html
  src/app/pipes/shared/ksi-date.pipe.ts
Labels: hacktoberfest-accepted

#79 feat(visual): better dark mode & unified code colors
  src/app/styles/colors.scss
  src/app/styles/theme.scss
  src/styles.scss
Labels: hacktoberfest-accepted

#78 feat(discussion): post size alert & info
  src/app/components/shared/modal-post-reply/modal-post-reply.component.html
  src/app/components/shared/modal-post-reply/modal-post-reply.component.scss
  src/app/components/shared/modal-post-reply/modal-post-reply.component.ts
  src/assets/i18n/cs.json
Labels: hacktoberfest-accepted
